# Base-Image
FROM python:3.11-slim

# Working Directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Standard 
CMD ["python", "main.py"]
